import SwiftUI
import StateKitMacros

@HookCallback
private struct SubmitQueryCallback {
    func call(_ query: String) -> String {
        "Submitted query: \(query)"
    }
}

struct UseCallback: View {
    var body: some View {
        StateScope {
            @HState var query = "swift"
            @HState var unrelatedCount = 0
            @HState var submitted = "Not submitted yet"

            let submit = useSubmitQueryCallback()

            VStack(alignment: .leading, spacing: 12) {
                TextField("Query", text: $query)
                    .textFieldStyle(.roundedBorder)

                Text(submitted)
                Text("Unrelated local state: \(unrelatedCount)")
                    .foregroundStyle(.secondary)

                Text("This callback is generated by @HookCallback and used as a reusable action.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                HStack {
                    Button("Submit") {
                        submitted = submit(query)
                    }
                    .buttonStyle(.borderedProminent)

                    Button("Change unrelated state") {
                        unrelatedCount += 1
                    }

                    Button("Preset query") {
                        query = "state-kit"
                    }
                }
                .buttonStyle(.bordered)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
}
