import SwiftUI
import StateKitMacros

@HookState
private struct LayoutEffectState {
    var step: Int = 0
}

@HookLayoutEffect
private struct StepLayoutEffect {
    var step: Int = 0

    func run() {
        print("layout effect for step \(step)")
    }
}

@HookEffect
private struct StepPassiveEffect {
    var step: Int = 0

    func run() async {
        print("passive effect for step \(step)")
    }
}

struct UseLayoutEffect: View {
    var body: some View {
        StateScope {
            let state = useLayoutEffectState()

            let step = state.wrappedValue.step

            let _ = useStepLayoutEffect(step: step)
            let _ = useStepPassiveEffect(step: step)

            VStack(alignment: .leading, spacing: 12) {
                Text("Current step: \(step)")

                Text("Both layout and passive effects are generated by macros.")
                    .font(.subheadline)
                    .foregroundStyle(.secondary)

                HStack {
                    Button("Next step") {
                        state.wrappedValue.step += 1
                    }
                    .buttonStyle(.borderedProminent)

                }
                .buttonStyle(.bordered)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
}
