import SwiftSyntax

/// Errors thrown when return type extraction fails.
enum ReturnTypeExtractor {
    enum ExtractionError: Error, CustomStringConvertible {
        /// No function with the given name was found in the declaration.
        case methodNotFound(String)
        /// The method exists but has no return clause.
        case noReturnType
        /// The type involved is generic in an unsupported way.
        case invalidGenericType
        /// The method uses `some Foo` (opaque return type), which cannot be used in a typealias.
        case opaqueReturnType(String)

        var description: String {
            switch self {
            case .methodNotFound(let name):
                return "Method '\(name)' not found in declaration"
            case .noReturnType:
                return "Method has no return type"
            case .invalidGenericType:
                return "Invalid or unsupported generic type"
            case .opaqueReturnType(let name):
                return "Method '\(name)' returns an opaque type ('some') — atoms require a concrete return type for the Value typealias"
            }
        }
    }

    /// Extract the return type from a method matching `methodName`.
    ///
    /// Throws `opaqueReturnType` if the return type uses `some` (opaque types
    /// cannot be used in `typealias` declarations generated by Atom macros).
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   struct MyAtom: ValueAtom {
    ///       func value(context: Context) -> Int { 42 }
    ///   }
    ///   // extract(from: myAtom, methodName: "value") → TypeSyntax("Int")
    ///
    ///   struct BadAtom: ValueAtom {
    ///       func value(context: Context) -> some Equatable { 42 }
    ///   }
    ///   // extract(from: badAtom, methodName: "value")
    ///   // → throws ExtractionError.opaqueReturnType("value")
    static func extract(from decl: DeclGroupSyntax, methodName: String) throws -> TypeSyntax {
        guard let function = function(in: decl, named: methodName) else {
            throw ExtractionError.methodNotFound(methodName)
        }

        guard let returnType = function.signature.returnClause?.type else {
            throw ExtractionError.noReturnType
        }

        let description = returnType.trimmedDescription
        guard !description.hasPrefix("some ") else {
            throw ExtractionError.opaqueReturnType(methodName)
        }

        return returnType
    }

    /// Find a function declaration by name within a struct/class/extension.
    ///
    /// If multiple overloads exist, prefers the one whose first parameter label
    /// is `context` (standard convention for Atom/Riverpod provider methods).
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   func value(context: Context) -> Int    // preferred by hasContextParameter
    ///   func value() -> Int                    // fallback
    static func function(in decl: DeclGroupSyntax, named: String) -> FunctionDeclSyntax? {
        findMethod(in: decl, named: named)
    }

    /// Strip wrapping type sugar: optional, IUO, attributes, `some`/`any`.
    ///
    /// Recursively peels off layers to get at the underlying concrete type.
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   Int?               → Int
    ///   Int!               → Int
    ///   @Sendable Int      → Int
    ///   some Equatable     → Equatable
    ///   any Numeric        → Numeric
    ///   Int                → Int  (no-op)
    static func unwrapType(_ type: TypeSyntax) -> TypeSyntax {
        if let optionalType = type.as(OptionalTypeSyntax.self) {
            return unwrapType(optionalType.wrappedType)
        }
        if let implicitlyUnwrappedOptionalType = type.as(ImplicitlyUnwrappedOptionalTypeSyntax.self) {
            return unwrapType(implicitlyUnwrappedOptionalType.wrappedType)
        }
        if let attributedType = type.as(AttributedTypeSyntax.self) {
            return unwrapType(attributedType.baseType)
        }
        if let someOrAnyType = type.as(SomeOrAnyTypeSyntax.self) {
            return unwrapType(someOrAnyType.constraint)
        }
        return type
    }

    /// Extract the Nth generic argument (0-indexed) from a type.
    ///
    /// Handles `IdentifierType` (e.g., `Array<Int>`), `MemberType` (e.g.,
    /// `Swift.Result<Int, Error>`), and recursively unwraps optionals,
    /// attributes, and `some`/`any`.
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   extractGenericArg(from: "Array<Int>", index: 0)   → Int
    ///   extractGenericArg(from: "Result<Data, Error>", index: 1) → Error
    ///   extractGenericArg(from: "Int", index: 0)          → Int (fallback)
    ///   extractGenericArg(from: "Int?", index: 0)         → Int
    static func extractGenericArg(from type: TypeSyntax, index: Int) throws -> TypeSyntax {
        let type = unwrapType(type)

        if let identifierType = type.as(IdentifierTypeSyntax.self),
           let genericArgs = identifierType.genericArgumentClause {
            let args = Array(genericArgs.arguments)
            if index < args.count {
                return TypeSyntax("\(raw: args[index].argument)")
            }
        }

        if let memberType = type.as(MemberTypeSyntax.self),
           let genericArgs = memberType.genericArgumentClause {
            let args = Array(genericArgs.arguments)
            if index < args.count {
                return TypeSyntax("\(raw: args[index].argument)")
            }
        }

        if let optionalType = type.as(OptionalTypeSyntax.self) {
            return try extractGenericArg(from: optionalType.wrappedType, index: index)
        }

        if let implicitlyUnwrappedOptionalType = type.as(ImplicitlyUnwrappedOptionalTypeSyntax.self) {
            return try extractGenericArg(from: implicitlyUnwrappedOptionalType.wrappedType, index: index)
        }

        if let attributedType = type.as(AttributedTypeSyntax.self) {
            return try extractGenericArg(from: attributedType.baseType, index: index)
        }

        if let someOrAnyType = type.as(SomeOrAnyTypeSyntax.self) {
            return try extractGenericArg(from: someOrAnyType.constraint, index: index)
        }

        return type
    }

    /// Resolve a typealias named `named` within a declaration to its underlying type string.
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   struct MyAtom: ValueAtom {
    ///       typealias Value = Int
    ///   }
    ///   // extractTypealias(from: myAtom, named: "Value") → "Int"
    static func extractTypealias(from decl: DeclGroupSyntax, named: String) throws -> String {
        for member in decl.memberBlock.members {
            if let typealiasDecl = member.decl.as(TypeAliasDeclSyntax.self),
               typealiasDecl.name.text == named {
                return typealiasDecl.initializer.value.description.trimmingCharacters(in: .whitespaces)
            }
        }
        throw ExtractionError.noReturnType
    }

    /// Check whether a method has a return clause at all.
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   hasReturnType(in: myAtom, methodName: "value") → true/false
    static func hasReturnType(in decl: DeclGroupSyntax, methodName: String) -> Bool {
        guard let function = function(in: decl, named: methodName) else { return false }
        return function.signature.returnClause != nil
    }

    /// Find the first matching function by name, preferring `context:` as first parameter.
    ///
    /// This is important because Atom/Riverpod protocols often have overloads
    /// like `value(context:)` and `value()`, and the `context:` variant is
    /// the one that defines the return type we need.
    private static func findMethod(in decl: DeclGroupSyntax, named: String) -> FunctionDeclSyntax? {
        let matches = decl.memberBlock.members.compactMap { member in
            member.decl.as(FunctionDeclSyntax.self).flatMap { $0.name.text == named ? $0 : nil }
        }
        if matches.isEmpty { return nil }
        if matches.count == 1 { return matches[0] }
        return matches.first(where: { hasContextParameter($0) }) ?? matches[0]
    }

    /// Whether the function's first parameter has external label `context`.
    private static func hasContextParameter(_ function: FunctionDeclSyntax) -> Bool {
        function.signature.parameterClause.parameters.first?.firstName.text == "context"
    }

    /// Check if a function is `async throws`.
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   func load() async throws -> Data   → true
    ///   func load() async -> Data          → false
    ///   func load() throws -> Data         → false
    static func isFunctionAsyncThrowing(_ function: FunctionDeclSyntax) -> Bool {
        let hasThrows = function.signature.effectSpecifiers?.throwsClause != nil
        let hasAsync = function.signature.effectSpecifiers?.asyncSpecifier != nil
        return hasThrows && hasAsync
    }

    /// Check if a function is `async` (non-throwing).
    ///
    /// ── Example ──────────────────────────────────────────────────────────
    ///   func load() async -> Data          → true
    ///   func load() async throws -> Data   → false
    ///   func load() -> Data                → false
    static func isFunctionAsync(_ function: FunctionDeclSyntax) -> Bool {
        let hasAsync = function.signature.effectSpecifiers?.asyncSpecifier != nil
        let hasThrows = function.signature.effectSpecifiers?.throwsClause != nil
        return hasAsync && !hasThrows
    }
}
